@startuml
Class StateEngine {
    -EnumSet states;
    -EnumSet events;
    -Enum currentState
    -Map<Enum, Map<Enum, Enum>> transitions

    +StateEngine (EnumSet states, EnumSet events, Enum startState)

    +void addTransition(Enum startState, Enum endState, Enum event)

    +Enum getCurrentState()

    +void performAction()
}
@enduml